In [ ]:
from IPython.core.display import display, HTML
display(HTML("""<a href="https://www.hackerrank.com/challenges/np-inner-and-outer/problem">text</a>"""))

In [82]:
import numpy as np

A = np.array(list(map(int,input().split(" "))))
B = np.array(list(map(int,input().split(" "))))
print(np.inner(A, B),np.outer(A,B), sep ="\n")

12 12 12
12 12 12
432
[[144 144 144]
 [144 144 144]
 [144 144 144]]
